In [12]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer,MissingIndicator

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [3]:
df=pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])

In [4]:
df.head()

,Survived,Age,Fare
0,0,22.0,7.2500
1,1,38.0,71.2833
2,1,26.0,7.9250
3,1,35.0,53.1000
4,0,35.0,8.0500


In [5]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

x_train,x_test,y_train,y_test=train_test_split(x,y,
                                               test_size=0.2,
                                               random_state=2)

In [8]:
x_train.tail()

,Age,Fare
534,30.0,8.6625
584,NaN,8.7125
493,71.0,49.5042
527,NaN,221.7792
168,NaN,25.9250


In [7]:
si=SimpleImputer()
x_train_trf=si.fit_transform(x_train)
x_test_trf=si.fit_transform(x_test)

In [10]:
x_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]], shape=(712, 2))

In [13]:
clf=LogisticRegression()
clf.fit(x_train_trf,y_train)
y_pred=clf.predict(x_test_trf)

accuracy_score(y_test,y_pred)

0.6145251396648045

<h1>Missing Indicator</h1>

In [16]:
mi=MissingIndicator()
x_train_mi=mi.fit_transform(x_train)
x_test_mi=mi.transform(x_test)

In [17]:
x_train_mi

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

<h2>Adding missing indicator cols to x_train and x_test</h2>

In [18]:
x_train['Age_NA']=x_train_mi
x_test['Age_NA']=x_test_mi

In [19]:
x_train

,Age,Fare,Age_NA
30,40.0,27.7208,False
10,4.0,16.7000,False
873,47.0,9.0000,False
182,9.0,31.3875,False
876,20.0,9.8458,False
...,...,...,...
534,30.0,8.6625,False
584,NaN,8.7125,True
493,71.0,49.5042,False
527,NaN,221.7792,True


In [20]:
x_test

,Age,Fare,Age_NA
707,42.0,26.2875,False
37,21.0,8.0500,False
615,24.0,65.0000,False
169,28.0,56.4958,False
68,17.0,7.9250,False
...,...,...,...
89,24.0,8.0500,False
80,22.0,9.0000,False
846,NaN,69.5500,True
870,26.0,7.8958,False


<h2>Simple Imputing original age col</h2>

In [21]:
si=SimpleImputer()
x_train_trf2=si.fit_transform(x_train)
x_test_trf2=si.transform(x_test)

In [23]:
clf=LogisticRegression()
clf.fit(x_train_trf2,y_train)
y_pred=clf.predict(x_test_trf2)

accuracy_score(y_test,y_pred)

0.6312849162011173

<h3>So, we notice slight improvement in model accuracy after missing indicator imputation.</h3>

<h1>Applying Missing Indicator using SimpleImputer</h1>

In [25]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

x_train,x_test,y_train,y_test=train_test_split(x,y,
                                               test_size=0.2,
                                               random_state=2)

In [24]:
si=SimpleImputer(add_indicator=True)

In [26]:
x_train_trf=si.fit_transform(x_train)
x_test_trf=si.transform(x_test)

In [27]:
x_train_trf

array([[ 40.        ,  27.7208    ,   0.        ],
       [  4.        ,  16.7       ,   0.        ],
       [ 47.        ,   9.        ,   0.        ],
       ...,
       [ 71.        ,  49.5042    ,   0.        ],
       [ 29.78590426, 221.7792    ,   1.        ],
       [ 29.78590426,  25.925     ,   1.        ]], shape=(712, 3))

In [28]:
clf=LogisticRegression()
clf.fit(x_train_trf,y_train)

y_pred=clf.predict(x_test_trf)

accuracy_score(y_test,y_pred)

0.6312849162011173